### ISSUE TITLE
[okr] Aeternity challenge

### ISSUE THREAD

**Issue by horohronos** [MVPWorkshop/MVPWGP#2]
Challenge 1:
Port your favorite aepp to aeternity to run it inside the base-aepp
The base-aepp branch that supports interaction with aepps is here: https://github.com/aeternity/aepp-base/pull/303

Challenge 2:
Build an easy to use paper-wallet generator with an UI that people can run locally.
You find an introduction to our command-line paper-wallet generator here:
https://dev.aepps.com/tutorials/create-a-paper-wallet.html
paper-wallet-cli:
https://github.com/aeternity/tool-paperwallets
Paperwallets can be used with our wallet base-aepp and redeem.aepps.com

Challenge 3:
Port your favorite auction contract to Sophia
https://dev.aepps.com/tutorials/owning-a-smart-contract.html
https://dev.aepps.com/tutorials/sophia-fungible-token-contract.html

Links:
Get Help & Discuss your ideas:
https://forum.aeternity.com/
Blockchain Protocol:
https://github.com/aeternity/protocol
JS-SDK:
https://github.com/aeternity/aepp-sdk-js
Python-SDK:
https://github.com/aeternity/aepp-sdk-python
Smart-Contract development:
https://github.com/aeternity/aepp-forgae-js

**Comment by fjovakaric** [comment]
@StefanBurscher 

- [How to create a paper wallet for aethernity](https://dev.aepps.com/tutorials/create-a-paper-wallet.html)

### Generate secure wallet with aepp-cli-js
- https://github.com/aeternity/aepp-cli-js/blob/develop/bin/utils/account.js
```
// Generate `keypair` encrypt it using password and write to `ethereum` keystore file
export async function generateSecureWallet (name, { output = '', password, overwrite }) {
  if (!overwrite && !(await askForOverwrite(name, output))) process.exit(0)
  password = password || await prompt(PROMPT_TYPE.askPassword)
  const { secretKey, publicKey } = Crypto.generateKeyPair(true)

  writeFile(path.join(output, name), JSON.stringify(await dump(name, password, secretKey)))

  printUnderscored('Address', Crypto.aeEncodeKey(publicKey))
  printUnderscored('Path', path.resolve(process.cwd(), path.join(output, name)))
}
```

### Generate keypair with aepp-sdk-js
- https://github.com/aeternity/aepp-sdk-js/blob/develop/es/utils/crypto.js
```
export function generateKeyPair (raw = false) {
  // <node>/apps/aens/test/aens_test_utils.erl
  const keyPair = nacl.sign.keyPair()

  const publicBuffer = Buffer.from(keyPair.publicKey)
  const secretBuffer = Buffer.from(keyPair.secretKey)

  if (raw) {
    return {
      publicKey: publicBuffer,
      secretKey: secretBuffer
    }
  } else {
    return {
      publicKey: `ak_${encodeBase58Check(publicBuffer)}`,
      secretKey: secretBuffer.toString('hex')
    }
  }
}
```

### Use nacl to create keypairs
- https://tweetnacl.js.org/#/
- https://github.com/dchest/tweetnacl-js/blob/master/nacl.js
```
nacl.sign.keyPair = function() {
  var pk = new Uint8Array(crypto_sign_PUBLICKEYBYTES);
  var sk = new Uint8Array(crypto_sign_SECRETKEYBYTES);
  crypto_sign_keypair(pk, sk);
  return {publicKey: pk, secretKey: sk};
};
```
